### ISSUE TITLE
Allow disabling documentation generation for some gems

### ISSUE THREAD

**Issue by Morriar** [Shopify/tapioca#1361]
Some gems such as `parser` or `rubocop` are known to slowing down Tapioca RBI generation.

While we are thinking about an alternative way to generate the documentation for all gems, it would be nice if Tapioca offered a mechanism to disable documentation generation on a per-gem basis.

Maybe something like this in the configuration:

```yml
gem:
  doc: true
  doc-exclude:
  - parser
  - rubocop
```
