### ISSUE TITLE
tapioca generates conflicting method signatures in gem and dsl

### ISSUE THREAD

**Issue by thomasdziedzic-census** [Shopify/tapioca#564]
context: https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1634675719155000

Someone posted that devise had this issue.

For me, it was the ddtrace gem.

The workaround is to put the following in your `sorbet/tapioca/config.yml`

```yaml
---
typed_overrides:
  'ddtrace': 'false'
```

where you replace ddtrace with the gem that is having issues and running `bin/tapioca gem ddtrace`.
