### ISSUE TITLE
Tapioca should check its config file

### ISSUE THREAD

**Issue by Morriar** [Shopify/tapioca#704]
For example, using:

```yaml
typed_overrides:
  "activesupport": "false"
```

Instead of: 

```yaml
gem:
  typed_overrides:
    "activesupport": "false"
```

Should make Tapioca generate a warning.

This will avoid some frustration as to why an option is not working and warn the user they need to update their config when we update Tapioca.
